/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author xLEMFx
 */
public class AcercaDe extends javax.swing.JFrame {

    /**
     * Creates new form AcercaDe
     */
    public AcercaDe() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcMousePanel1 = new jcMousePanel.jcMousePanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jcMousePanel2 = new jcMousePanel.jcMousePanel();
        jcMousePanel3 = new jcMousePanel.jcMousePanel();
        jLabel2 = new javax.swing.JLabel();
        jcMousePanel5 = new jcMousePanel.jcMousePanel();
        jcMousePanel4 = new jcMousePanel.jcMousePanel();
        jcMousePanel6 = new jcMousePanel.jcMousePanel();
        jcMousePanel7 = new jcMousePanel.jcMousePanel();
        jcMousePanel8 = new jcMousePanel.jcMousePanel();
        jcMousePanel9 = new jcMousePanel.jcMousePanel();
        jcMousePanel10 = new jcMousePanel.jcMousePanel();
        jcMousePanel11 = new jcMousePanel.jcMousePanel();
        jcMousePanel12 = new jcMousePanel.jcMousePanel();
        jcMousePanel13 = new jcMousePanel.jcMousePanel();
        jLabel7 = new javax.swing.JLabel();
        jcMousePanel15 = new jcMousePanel.jcMousePanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(750, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jcMousePanel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logos/-Icono sena v3.png"))); // NOI18N
        getContentPane().add(jcMousePanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 100, 70));

        jLabel5.setFont(new java.awt.Font("Hand Of Sean (Demo)", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 153));
        jLabel5.setText("SoftIng");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 20, 160, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Temas/-Barra naranjado.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 90));

        jLabel4.setText("LIDER DE PROYECTO ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        jLabel6.setText("DOCUMENTACION ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, -1, -1));

        jLabel8.setText("PROGRAMACIÓN");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 140, -1, -1));

        jLabel9.setText("DISEÑO");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 140, -1, -1));

        jLabel10.setText("PRUEBAS");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 140, 60, 20));

        jLabel11.setText("BASE DE DATOS");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 140, -1, 10));

        jButton1.setFont(new java.awt.Font("Hand Of Sean (Demo)", 0, 14)); // NOI18N
        jButton1.setText("Atras");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 660, -1, -1));

        jcMousePanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Brayan Feria Palomino", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Hand Of Sean (Demo)", 0, 12))); // NOI18N
        jcMousePanel2.setFont(new java.awt.Font("Hand Of Sean (Demo)", 1, 10)); // NOI18N
        jcMousePanel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BRAYAN SNEIDER FERIA PALOMINO.jpg"))); // NOI18N
        jcMousePanel2.setInheritsPopupMenu(true);

        javax.swing.GroupLayout jcMousePanel2Layout = new javax.swing.GroupLayout(jcMousePanel2);
        jcMousePanel2.setLayout(jcMousePanel2Layout);
        jcMousePanel2Layout.setHorizontalGroup(
            jcMousePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 148, Short.MAX_VALUE)
        );
        jcMousePanel2Layout.setVerticalGroup(
            jcMousePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 116, Short.MAX_VALUE)
        );

        getContentPane().add(jcMousePanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 490, 160, 140));

        jcMousePanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Liseth Esquivel Molina", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Hand Of Sean (Demo)", 0, 12))); // NOI18N
        jcMousePanel3.setFont(new java.awt.Font("Hand Of Sean (Demo)", 1, 10)); // NOI18N
        jcMousePanel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LISETH YERARDING ESQUIVEL MOLINA.jpg"))); // NOI18N

        javax.swing.GroupLayout jcMousePanel3Layout = new javax.swing.GroupLayout(jcMousePanel3);
        jcMousePanel3.setLayout(jcMousePanel3Layout);
        jcMousePanel3Layout.setHorizontalGroup(
            jcMousePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 188, Short.MAX_VALUE)
        );
        jcMousePanel3Layout.setVerticalGroup(
            jcMousePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 186, Short.MAX_VALUE)
        );

        getContentPane().add(jcMousePanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 200, 210));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Temas/-Barra Verde35% Azul 65%.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 640, 1390, 70));

        jcMousePanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Karol Sanchez Garcia", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Hand Of Sean (Demo)", 0, 12))); // NOI18N
        jcMousePanel5.setFont(new java.awt.Font("Hand Of Sean (Demo)", 1, 10)); // NOI18N
        jcMousePanel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/P1210704.JPG"))); // NOI18N
        jcMousePanel5.setInheritsPopupMenu(true);

        javax.swing.GroupLayout jcMousePanel5Layout = new javax.swing.GroupLayout(jcMousePanel5);
        jcMousePanel5.setLayout(jcMousePanel5Layout);
        jcMousePanel5Layout.setHorizontalGroup(
            jcMousePanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 148, Short.MAX_VALUE)
        );
        jcMousePanel5Layout.setVerticalGroup(
            jcMousePanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 126, Short.MAX_VALUE)
        );

        getContentPane().add(jcMousePanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 370, 160, 150));

        jcMousePanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Jaider Mercado Lopez.", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Hand Of Sean (Demo)", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jcMousePanel4.setForeground(new java.awt.Color(255, 255, 255));
        jcMousePanel4.setFont(new java.awt.Font("Hand Of Sean (Demo)", 1, 10)); // NOI18N
        jcMousePanel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/jaider mercado.jpg"))); // NOI18N

        javax.swing.GroupLayout jcMousePanel4Layout = new javax.swing.GroupLayout(jcMousePanel4);
        jcMousePanel4.setLayout(jcMousePanel4Layout);
        jcMousePanel4Layout.setHorizontalGroup(
            jcMousePanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 158, Short.MAX_VALUE)
        );
        jcMousePanel4Layout.setVerticalGroup(
            jcMousePanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 126, Short.MAX_VALUE)
        );

        getContentPane().add(jcMousePanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 180, 170, 150));

        jcMousePanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Arceya Higuita Valencia", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Hand Of Sean (Demo)", 0, 12))); // NOI18N
        jcMousePanel6.setFont(new java.awt.Font("Hand Of Sean (Demo)", 1, 10)); // NOI18N
        jcMousePanel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/P1210706.JPG"))); // NOI18N
        jcMousePanel6.setInheritsPopupMenu(true);

        javax.swing.GroupLayout jcMousePanel6Layout = new javax.swing.GroupLayout(jcMousePanel6);
        jcMousePanel6.setLayout(jcMousePanel6Layout);
        jcMousePanel6Layout.setHorizontalGroup(
            jcMousePanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 158, Short.MAX_VALUE)
        );
        jcMousePanel6Layout.setVerticalGroup(
            jcMousePanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 126, Short.MAX_VALUE)
        );

        getContentPane().add(jcMousePanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, 170, 150));

        jcMousePanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Luisa Parada Lozada", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Hand Of Sean (Demo)", 0, 12))); // NOI18N
        jcMousePanel7.setFont(new java.awt.Font("Hand Of Sean (Demo)", 1, 10)); // NOI18N
        jcMousePanel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/P1210708.JPG"))); // NOI18N
        jcMousePanel7.setInheritsPopupMenu(true);

        javax.swing.GroupLayout jcMousePanel7Layout = new javax.swing.GroupLayout(jcMousePanel7);
        jcMousePanel7.setLayout(jcMousePanel7Layout);
        jcMousePanel7Layout.setHorizontalGroup(
            jcMousePanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 148, Short.MAX_VALUE)
        );
        jcMousePanel7Layout.setVerticalGroup(
            jcMousePanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 126, Short.MAX_VALUE)
        );

        getContentPane().add(jcMousePanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 160, 150));

        jcMousePanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Andres Amaya Suarez", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Hand Of Sean (Demo)", 0, 12))); // NOI18N
        jcMousePanel8.setFont(new java.awt.Font("Hand Of Sean (Demo)", 1, 10)); // NOI18N
        jcMousePanel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/P1210707.JPG"))); // NOI18N
        jcMousePanel8.setInheritsPopupMenu(true);

        javax.swing.GroupLayout jcMousePanel8Layout = new javax.swing.GroupLayout(jcMousePanel8);
        jcMousePanel8.setLayout(jcMousePanel8Layout);
        jcMousePanel8Layout.setHorizontalGroup(
            jcMousePanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 158, Short.MAX_VALUE)
        );
        jcMousePanel8Layout.setVerticalGroup(
            jcMousePanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 116, Short.MAX_VALUE)
        );

        getContentPane().add(jcMousePanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 330, 170, 140));

        jcMousePanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Guillermo Niebles Vasquez", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Hand Of Sean (Demo)", 0, 12))); // NOI18N
        jcMousePanel9.setFont(new java.awt.Font("Hand Of Sean (Demo)", 1, 10)); // NOI18N
        jcMousePanel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/P1210712.JPG"))); // NOI18N
        jcMousePanel9.setInheritsPopupMenu(true);

        javax.swing.GroupLayout jcMousePanel9Layout = new javax.swing.GroupLayout(jcMousePanel9);
        jcMousePanel9.setLayout(jcMousePanel9Layout);
        jcMousePanel9Layout.setHorizontalGroup(
            jcMousePanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 168, Short.MAX_VALUE)
        );
        jcMousePanel9Layout.setVerticalGroup(
            jcMousePanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 126, Short.MAX_VALUE)
        );

        getContentPane().add(jcMousePanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 180, 150));

        jcMousePanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Jefferson Vargas Silva", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Hand Of Sean (Demo)", 0, 12))); // NOI18N
        jcMousePanel10.setFont(new java.awt.Font("Hand Of Sean (Demo)", 1, 10)); // NOI18N
        jcMousePanel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/P1210710.JPG"))); // NOI18N
        jcMousePanel10.setInheritsPopupMenu(true);

        javax.swing.GroupLayout jcMousePanel10Layout = new javax.swing.GroupLayout(jcMousePanel10);
        jcMousePanel10.setLayout(jcMousePanel10Layout);
        jcMousePanel10Layout.setHorizontalGroup(
            jcMousePanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 158, Short.MAX_VALUE)
        );
        jcMousePanel10Layout.setVerticalGroup(
            jcMousePanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 116, Short.MAX_VALUE)
        );

        getContentPane().add(jcMousePanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 490, 170, 140));

        jcMousePanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Johan Ortiz Alvarino", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Hand Of Sean (Demo)", 0, 12))); // NOI18N
        jcMousePanel11.setFont(new java.awt.Font("Hand Of Sean (Demo)", 1, 10)); // NOI18N
        jcMousePanel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/P1210715.JPG"))); // NOI18N
        jcMousePanel11.setInheritsPopupMenu(true);

        javax.swing.GroupLayout jcMousePanel11Layout = new javax.swing.GroupLayout(jcMousePanel11);
        jcMousePanel11.setLayout(jcMousePanel11Layout);
        jcMousePanel11Layout.setHorizontalGroup(
            jcMousePanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 148, Short.MAX_VALUE)
        );
        jcMousePanel11Layout.setVerticalGroup(
            jcMousePanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 116, Short.MAX_VALUE)
        );

        getContentPane().add(jcMousePanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 180, 160, 140));

        jcMousePanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Luis Morales Florez", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Hand Of Sean (Demo)", 0, 12))); // NOI18N
        jcMousePanel12.setFont(new java.awt.Font("Hand Of Sean (Demo)", 1, 10)); // NOI18N
        jcMousePanel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/P1210711.JPG"))); // NOI18N
        jcMousePanel12.setInheritsPopupMenu(true);

        javax.swing.GroupLayout jcMousePanel12Layout = new javax.swing.GroupLayout(jcMousePanel12);
        jcMousePanel12.setLayout(jcMousePanel12Layout);
        jcMousePanel12Layout.setHorizontalGroup(
            jcMousePanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 138, Short.MAX_VALUE)
        );
        jcMousePanel12Layout.setVerticalGroup(
            jcMousePanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 116, Short.MAX_VALUE)
        );

        getContentPane().add(jcMousePanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 330, 150, 140));

        jcMousePanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Yuri Ibañez Navarro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Hand Of Sean (Demo)", 0, 12))); // NOI18N
        jcMousePanel13.setFont(new java.awt.Font("Hand Of Sean (Demo)", 1, 10)); // NOI18N
        jcMousePanel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/YURI KATHERINE IBANEZ NAVARRO.jpg"))); // NOI18N
        jcMousePanel13.setInheritsPopupMenu(true);

        javax.swing.GroupLayout jcMousePanel13Layout = new javax.swing.GroupLayout(jcMousePanel13);
        jcMousePanel13.setLayout(jcMousePanel13Layout);
        jcMousePanel13Layout.setHorizontalGroup(
            jcMousePanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 148, Short.MAX_VALUE)
        );
        jcMousePanel13Layout.setVerticalGroup(
            jcMousePanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 116, Short.MAX_VALUE)
        );

        getContentPane().add(jcMousePanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 180, 160, 140));

        jLabel7.setText("ANÁLISIS");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, -1, -1));

        jcMousePanel15.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lucia Mantilla Blanco", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Hand Of Sean (Demo)", 0, 12))); // NOI18N
        jcMousePanel15.setFont(new java.awt.Font("Hand Of Sean (Demo)", 1, 10)); // NOI18N
        jcMousePanel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/OLGA LUCÍA MANTILLA BLANCO.jpg"))); // NOI18N

        javax.swing.GroupLayout jcMousePanel15Layout = new javax.swing.GroupLayout(jcMousePanel15);
        jcMousePanel15.setLayout(jcMousePanel15Layout);
        jcMousePanel15Layout.setHorizontalGroup(
            jcMousePanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 148, Short.MAX_VALUE)
        );
        jcMousePanel15Layout.setVerticalGroup(
            jcMousePanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 126, Short.MAX_VALUE)
        );

        getContentPane().add(jcMousePanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 180, 160, 150));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Temas/maxresdefault.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 80, 1470, 640));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
new Inicio().setVisible(true);
this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AcercaDe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AcercaDe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AcercaDe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AcercaDe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AcercaDe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private jcMousePanel.jcMousePanel jcMousePanel1;
    private jcMousePanel.jcMousePanel jcMousePanel10;
    private jcMousePanel.jcMousePanel jcMousePanel11;
    private jcMousePanel.jcMousePanel jcMousePanel12;
    private jcMousePanel.jcMousePanel jcMousePanel13;
    private jcMousePanel.jcMousePanel jcMousePanel15;
    private jcMousePanel.jcMousePanel jcMousePanel2;
    private jcMousePanel.jcMousePanel jcMousePanel3;
    private jcMousePanel.jcMousePanel jcMousePanel4;
    private jcMousePanel.jcMousePanel jcMousePanel5;
    private jcMousePanel.jcMousePanel jcMousePanel6;
    private jcMousePanel.jcMousePanel jcMousePanel7;
    private jcMousePanel.jcMousePanel jcMousePanel8;
    private jcMousePanel.jcMousePanel jcMousePanel9;
    // End of variables declaration//GEN-END:variables
}
