
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ANDRES
 */
public class InicioVigilante extends javax.swing.JFrame {

     Conexion ctm = new Conexion();
    Connection registro = ctm.conexion();
    private  static String cadena = "0123456789abcdefghijklmnopqrstuvwxyz";
    
    
    public InicioVigilante() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jcMousePanel1 = new jcMousePanel.jcMousePanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Myriad Pro", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setText("Seleccione una opcion");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 290, 40));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 1050, 20));

        jLabel8.setFont(new java.awt.Font("Myriad Pro", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("VIGILANTE");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 30, 170, 40));

        jButton2.setFont(new java.awt.Font("Myriad Pro", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/door exit 30.png"))); // NOI18N
        jButton2.setText("CERRAR SESION");
        jButton2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Myriad Pro", 1, 18))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 640, 190, 40));

        jLabel5.setFont(new java.awt.Font("Myriad Pro", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 153));
        jLabel5.setText("SoftIng");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Temas/-Barra Verde35% Azul 65%.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 610, 1390, 130));

        jButton4.setFont(new java.awt.Font("Myriad Pro", 1, 18)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/looking blue 40.png"))); // NOI18N
        jButton4.setText("CONSULTAR");
        jButton4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Myriad Pro", 1, 18))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 120, 190, 60));

        jButton6.setFont(new java.awt.Font("Myriad Pro", 1, 18)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Laptop_35761.png"))); // NOI18N
        jButton6.setText("REGISTRAR DISPOSITIVO");
        jButton6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Myriad Pro", 1, 18))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 300, 280, 60));

        jButton5.setFont(new java.awt.Font("Myriad Pro", 1, 18)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/addmale 40.png"))); // NOI18N
        jButton5.setText("REGISTRAR PERSONA");
        jButton5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Myriad Pro", 1, 18))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 280, 60));

        jcMousePanel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logos/-Icono sena v3.png"))); // NOI18N
        getContentPane().add(jcMousePanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 100, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Temas/-Barra naranjado.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 90));

        jButton1.setFont(new java.awt.Font("Myriad Pro", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Ok 30.png"))); // NOI18N
        jButton1.setText("INGRESAR DISPOSITIVO");
        jButton1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Myriad Pro", 1, 18))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, 280, 60));

        jButton3.setFont(new java.awt.Font("Myriad Pro", 1, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/exit 30.png"))); // NOI18N
        jButton3.setText("    SALIDA DISPOSITIVO   ");
        jButton3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Myriad Pro", 1, 18))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 430, 280, 60));

        jLabel3.setFont(new java.awt.Font("Myriad Pro", 1, 24)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Temas/maxresdefault.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1420, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
new Inicio().setVisible(true);
this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
ConsultasVigilante InicioVigilante = new ConsultasVigilante();
this.setVisible(false);
InicioVigilante.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
RegistrarPersonaVigilante InicioVigilante = new RegistrarPersonaVigilante();
this.setVisible(false);
InicioVigilante.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
   

        
        RegistrarDispoVigilante InicioVigilante = new RegistrarDispoVigilante();
this.setVisible(false);
InicioVigilante.setVisible(true);
int longitudCad = cadena.length();

                String clave = "";
                String caracter = "";
                
                 for (int i = 0; i < 6; i++) {
                    int numero = (int) (Math.random() * (longitudCad));
                    caracter = cadena.substring(numero, numero + 1);
                    clave = clave + caracter;
                }
               //  codigo generador= new codigo();//"Frame2" es el nombre que tu le pusiste a tu 2do jframe
         
         RegistrarDispoVigilante.jTextField9.setText(clave);


               


    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
Confirmacionexisp InicioVigilante = new Confirmacionexisp();
this.setVisible(false);
InicioVigilante.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Confirmacionexispsal InicioVigilante = new Confirmacionexispsal();
        this.setVisible(false);
        InicioVigilante.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioVigilante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioVigilante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioVigilante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioVigilante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioVigilante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private jcMousePanel.jcMousePanel jcMousePanel1;
    // End of variables declaration//GEN-END:variables

       
//    public void azarverificado(){    
//azar();
// int longitudCad = cadena.length();
//
//
//                String clavepeq = "";
//                String caracter = "";
//                String clavemon = "";
//                
//                 for (int i = 0; i < 6; i++) {
//                    int numero = (int) (Math.random() * (longitudCad));
//                    caracter = cadena.substring(numero, numero + 1);
//                    clavepeq = clavepeq + caracter;
//                    clavemon = clavepeq;
//                    //JOptionPane.showConfirmDialog(null, "La clave es:"+clavepeq );
//                }
//                 JOptionPane.showConfirmDialog(null, "La clave es:"+clavepeq );
//                 //RegistrarDispoVigilante.jTextField9.setText(clavepeq);
//try{
//                     JOptionPane.showConfirmDialog(null, "voy dentro del try" );
//            java.sql.Statement estado = registro.createStatement();
//            ResultSet res = estado.executeQuery("select Serial_dispositivo from dispositivo where Serial_dispositivo ='"+clavemon+"';");
//            
//             JOptionPane.showConfirmDialog(null,"voy despues de la consulta, el numero que se ingreso a la consulta es:"+clavemon );
//             
//                while(res.next()){
//                 JOptionPane.showConfirmDialog(null, "voy despues del guile" );
//                 
//                rek = res.getString("Serial_dispositivo");    
//                                 JOptionPane.showConfirmDialog(null, "el resultado de la consulta es:"+rek );
//        
//                    if(!rek.contentEquals(clavemon)){                        
//                    RegistrarDispoVigilante InicioVigilante = new RegistrarDispoVigilante();
//                    InicioVigilante.setVisible(true);
//                    RegistrarDispoVigilante.jTextField9.setText(clavemon);
//                    }
//                    
//                    //JOHAN SI QUIERE CONTINUAR RECUERDE NO PEDIR UNA VARIABLE VACIAS, SINO TAMBIEN UN UVARABIEL SOLA.
//                   
//            }
//             if(rek.equals(clavemon)){
//                    JOptionPane.showConfirmDialog(null, "Aqui voy con la clave"+clavemon+"\n y la clave ya existe en la base de datos" );
//                    }
//        }catch(Exception e){
//            System.out.println(e.toString()); 
//        };
//        
//    }
//    
//    public void azar(){
//        int longitudCad = cadena.length();
//
//
//                String clave = "";
//                String caracter = "";
//                
//                 for (int i = 0; i < 6; i++) {
//                    int numero = (int) (Math.random() * (longitudCad));
//                    caracter = cadena.substring(numero, numero + 1);
//                    clave = clave + caracter;
//                }
//    }



}
